---
- hosts: localhost
  connection: local
  vars:
    ami: "ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"
  tasks:
    - name: create dummy ec2 instance
      ec2:
        region: "ap-southeast-1"
        key_name: "test-instance"
        instance_type: t2.nano
        image: "{{ ami | latest_ami_id('ap-southeast-1', ami_owner_id='099720109477') }}"
        wait: true
        group: "w77-office-app"
        exact_count: 2
        count_tag:
          Cluster: "test-ansible"
        vpc_subnet_id: "subnet-9eb519e8"
        instance_tags:
          Cluster: "test-ansible"

    - name: gather ec2 ip from newly created cluster
      add_host:
        name: "{{ item }}"
        groups: new_group
      with_items: "{{ 'ap-southeast-1' | get_instances_by_tags(Cluster='test-ansible', state='running') }}"

    - name: wait for ssh
      wait_for:
        port: 22
        host: "{{ item }}"
        timeout: 600
        state: started
      with_items: "{{ 'ap-southeast-1' | get_instances_by_tags(Cluster='test-ansible', state='running') }}"

- hosts: new_group
  tasks:
    - name: get hostname
      command: hostname
